import { Sparkles } from 'lucide-react';
import LegalPageLayout from '@/components/legal/LegalPageLayout';

/**
 * AI Disclosure & Responsible Use Statement.
 *
 * Discloses where and how Brikly uses AI/ML, the limits of those features,
 * data-handling practices, training-data policy, and human-oversight
 * obligations. Helps satisfy the Colorado AI Act, NYC Local Law 144 (where
 * applicable), the EU AI Act for EU-facing products, and FTC guidance on
 * AI claims.
 */
const AIDisclosure = () => (
  <LegalPageLayout
    title="AI Disclosure & Responsible Use"
    metaDescription="How Brikly uses artificial intelligence, what data is shared with AI providers, the limitations of AI outputs, and your responsibilities when using AI features."
    effectiveDate="April 13, 2026"
    lastUpdated="April 13, 2026"
    icon={<Sparkles className="h-5 w-5 text-primary" aria-hidden="true" />}
    relatedLinks={[
      { label: 'Privacy Policy', href: '/privacy-policy' },
      { label: 'Acceptable Use Policy', href: '/acceptable-use-policy' },
      { label: 'Subprocessors', href: '/subprocessors' },
    ]}
  >
    <h2>1. Where Brikly Uses AI</h2>
    <p>
      Brikly uses artificial-intelligence and machine-learning features ("<strong>AI Features</strong>")
      in the following areas of the Service:
    </p>
    <ul>
      <li>
        <strong>AI Estimating</strong> — generates draft estimates and line items based on project
        descriptions and historical cost data.
      </li>
      <li>
        <strong>AI Insights &amp; Project Assistant</strong> — produces written summaries,
        recommendations, risk indicators, and Q&amp;A responses about a project.
      </li>
      <li>
        <strong>Image &amp; Document Analysis</strong> — classifies photos, extracts text from
        receipts and drawings (OCR), and tags content.
      </li>
      <li>
        <strong>Quality Control &amp; Safety Insights</strong> — flags potential anomalies in
        inspection photos and daily reports for human review.
      </li>
      <li>
        <strong>Marketing / Blog Generation</strong> — assists in drafting marketing content for
        publication on the customer's behalf.
      </li>
      <li>
        <strong>Support Triage</strong> — routes and summarizes incoming support tickets internally
        at Brikly.
      </li>
    </ul>

    <h2>2. Output Labeling</h2>
    <p>
      Content generated or materially assisted by AI is labeled within the Service (for example,
      with a "Generated by AI" badge). Customers who use AI features to publish content externally
      remain responsible for any disclosures required by the platform on which the content is
      posted (e.g., FTC endorsement guides).
    </p>

    <h2>3. Limitations &amp; Your Responsibility</h2>
    <p>
      AI Features can produce outputs that are inaccurate, incomplete, biased, or out of date. They
      do not constitute professional advice (engineering, accounting, legal, medical, employment).
      You must:
    </p>
    <ul>
      <li>Independently review and verify AI outputs before relying on them;</li>
      <li>
        Apply human judgment to any decision that has legal or similarly significant effects on a
        person (employment, hiring, lending, housing, benefits, discipline);
      </li>
      <li>
        Comply with applicable laws governing the use of AI in your jurisdiction (including the
        Colorado AI Act, NYC Local Law 144, the Illinois AI Video Interview Act, the EU AI Act, and
        sector-specific rules); and
      </li>
      <li>Not use AI outputs to discriminate or to evade obligations under anti-discrimination law.</li>
    </ul>

    <h2>4. Data Sent to AI Providers</h2>
    <p>
      When you invoke an AI Feature, the inputs you provide (text, file content, or selected fields)
      may be transmitted to a third-party AI provider listed in our{' '}
      <a href="/subprocessors">Subprocessors</a> page (currently Anthropic and OpenAI; which
      provider handles a given feature is listed there). We have contracts with these providers
      that:
    </p>
    <ul>
      <li>Limit use of customer inputs and outputs to providing the requested service;</li>
      <li>Prohibit the provider from using customer data to train its general models;</li>
      <li>Require deletion within a defined retention window after processing.</li>
    </ul>
    <p>
      Aggregated, de-identified usage statistics may be retained to monitor performance and detect
      abuse. We do not sell AI inputs or outputs.
    </p>

    <h2>5. Training of Brikly Models</h2>
    <p>
      Brikly does <strong>not</strong> use Customer Personal Data or Customer Content to train
      foundation models. Customer-facing model improvements are based on (a) explicit customer
      feedback ("thumbs up/down"), (b) anonymized and aggregated usage analytics, and (c) data the
      customer has expressly opted-in to share for model improvement (none enabled by default).
    </p>

    <h2>6. Human Oversight &amp; Override</h2>
    <p>
      A human override is available for every consequential AI Feature. You may always edit, reject,
      or replace AI-generated content before it is saved, sent, or published. AI estimates,
      financial projections, and safety insights present a confidence indicator and supporting data
      so reviewers can assess them.
    </p>

    <h2>7. Bias &amp; Quality Monitoring</h2>
    <p>
      We periodically review AI Features for accuracy, bias, and disparate impact, and we maintain
      an internal AI risk register. Customers may report concerns to{' '}
      <a href="mailto:ai@brikly.net">ai@brikly.net</a>.
    </p>

    <h2>8. Opting Out</h2>
    <p>
      Workspace administrators can disable AI Features for the entire workspace from{' '}
      <a href="/company-settings">Company Settings &rarr; AI</a>. Individual users can choose not
      to invoke optional AI Features.
    </p>

    <h2>9. Changes</h2>
    <p>
      We will update this disclosure when we add new AI Features or change AI providers. Material
      changes will be announced at least 30 days in advance through the Service or by email.
    </p>
  </LegalPageLayout>
);

export default AIDisclosure;
