import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { AIGeneratedBadge } from '@/components/ui/ai-generated-badge';

describe('AIGeneratedBadge', () => {
  it('states its meaning in text, not by icon or colour alone', () => {
    render(<AIGeneratedBadge />);
    expect(screen.getByText('Generated by AI')).toBeInTheDocument();
  });

  it('accepts a more precise label', () => {
    render(<AIGeneratedBadge label="AI estimate" />);
    expect(screen.getByText('AI estimate')).toBeInTheDocument();
  });

  it('carries a review instruction for assistive tech', () => {
    const { container } = render(<AIGeneratedBadge />);
    expect(container.querySelector('[title]')?.getAttribute('title')).toMatch(/review it/i);
  });

  it('hides the decorative icon from assistive tech', () => {
    const { container } = render(<AIGeneratedBadge />);
    const icon = container.querySelector('svg');
    expect(icon?.getAttribute('aria-hidden')).toBe('true');
  });
});
