import {
  AlertTriangle,
  BarChart3,
  BarChart4,
  Bot,
  Brain,
  Building2,
  Calendar,
  Calendar as CalendarIcon,
  Code,
  DollarSign,
  FileText,
  Globe,
  HelpCircle,
  Key,
  Layers,
  Lock,
  MapPin,
  MessageSquare,
  Settings,
  Shield,
  Tag,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  Webhook,
  Zap,
} from "lucide-react";
import type { NavigationArea } from "./types";

export const adminArea: NavigationArea = {
  id: "admin",
  title: "Admin",
  icon: Shield,
  sections: [
    {
      id: "system_admin",
      label: "System Administration",
      items: [
        {
          title: "Companies",
          url: "/admin/companies",
          icon: Building2,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Users",
          url: "/admin/users",
          icon: Users,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "System Settings",
          url: "/admin/settings",
          icon: Settings,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "System Admin Settings",
          url: "/system-admin/settings",
          icon: Settings,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "AI Models",
          url: "/admin/ai-models",
          icon: Zap,
          roles: ["root_admin"],
          badge: "Admin",
        },
      ],
    },
    {
      id: "business_admin",
      label: "Business Administration",
      items: [
        {
          title: "Billing",
          url: "/admin/billing",
          icon: DollarSign,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Promotions",
          url: "/admin/promotions",
          icon: Tag,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Upgrade Plan",
          url: "/upgrade",
          icon: TrendingUp,
          roles: ["admin", "root_admin"],
        },
      ],
    },
    {
      id: "marketing_growth",
      label: "Marketing & Growth",
      items: [
        {
          title: "Lead Management",
          url: "/admin/leads",
          icon: UserPlus,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Demo Management",
          url: "/admin/demos",
          icon: CalendarIcon,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Conversion Analytics",
          url: "/admin/conversion-analytics",
          icon: Target,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Retention Analytics",
          url: "/admin/retention-analytics",
          icon: TrendingUp,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Revenue Analytics",
          url: "/admin/revenue-analytics",
          icon: DollarSign,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Churn Prediction",
          url: "/admin/churn-prediction",
          icon: AlertTriangle,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Customer Intelligence",
          url: "/admin/intelligence",
          icon: Brain,
          roles: ["admin", "root_admin"],
        },
      ],
    },
    {
      id: "ai_intelligence",
      label: "AI Intelligence",
      items: [
        {
          title: "AI Estimating",
          url: "/admin/ai-estimating",
          icon: Brain,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Risk Prediction",
          url: "/admin/risk-prediction",
          icon: AlertTriangle,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Auto Scheduling",
          url: "/admin/auto-scheduling",
          icon: Calendar,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Safety Automation",
          url: "/admin/safety-automation",
          icon: Shield,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Smart Procurement",
          url: "/admin/smart-procurement",
          icon: Bot,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Advanced Dashboards",
          url: "/admin/advanced-dashboards",
          icon: BarChart4,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Client Portal Pro",
          url: "/admin/client-portal-pro",
          icon: Users,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Billing Automation",
          url: "/admin/billing-automation",
          icon: DollarSign,
          roles: ["root_admin"],
          badge: "AI",
        },
        {
          title: "Reporting Engine",
          url: "/admin/reporting-engine",
          icon: FileText,
          roles: ["root_admin"],
          badge: "AI",
        },
      ],
    },
    {
      id: "tenant_enterprise",
      label: "Tenant & Enterprise",
      items: [
        {
          title: "Tenant Management",
          url: "/admin/tenants",
          icon: Layers,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "SSO Management",
          url: "/admin/sso",
          icon: Lock,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Permission Management",
          url: "/admin/permissions",
          icon: Shield,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Audit Logging",
          url: "/admin/audit",
          icon: FileText,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Error Logs",
          url: "/admin/error-logs",
          icon: AlertTriangle,
          roles: ["root_admin", "admin"],
          badge: "New",
        },
      ],
    },
    {
      id: "developer_tools",
      label: "Developer Tools",
      items: [
        {
          title: "API Key Management",
          url: "/admin/api-keys",
          icon: Key,
          roles: ["root_admin"],
          badge: "Dev",
        },
        {
          title: "Webhook Management",
          url: "/admin/webhooks",
          icon: Webhook,
          roles: ["root_admin"],
          badge: "Dev",
        },
        {
          title: "Developer Portal",
          url: "/admin/developer-portal",
          icon: Code,
          roles: ["root_admin"],
          badge: "Dev",
        },
      ],
    },
    {
      id: "field_operations",
      label: "Field Operations",
      items: [
        {
          title: "GPS Time Tracking",
          url: "/admin/gps-tracking",
          icon: MapPin,
          roles: ["root_admin"],
          badge: "Admin",
        },
      ],
    },
    {
      id: "content_admin",
      label: "Content Administration",
      items: [
        {
          title: "Blog Manager",
          url: "/blog-manager",
          icon: MessageSquare,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Knowledge Base Admin",
          url: "/knowledge-base-admin",
          icon: FileText,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Social Media Manager",
          url: "/admin/social-media",
          icon: MessageSquare,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "SEO Management",
          url: "/admin/seo-management",
          icon: Globe,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "SEO Audit Tools",
          url: "/admin/seo",
          icon: Target,
          roles: ["admin", "root_admin"],
          description: "Site audit, crawl, keyword positions and backlinks",
        },
        {
          title: "Search Traffic",
          url: "/admin/search-traffic-dashboard",
          icon: BarChart3,
          roles: ["root_admin"],
        },
        {
          title: "Programmatic SEO",
          url: "/admin/pseo",
          icon: Globe,
          roles: ["admin", "root_admin"],
        },
        {
          title: "Analytics",
          url: "/admin/analytics",
          icon: TrendingUp,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Funnels",
          url: "/admin/funnels",
          icon: Zap,
          roles: ["root_admin"],
          badge: "Admin",
        },
      ],
    },
    {
      id: "support_admin",
      label: "Support Administration",
      items: [
        {
          title: "Support Tickets",
          url: "/admin/support-tickets",
          icon: HelpCircle,
          roles: ["admin", "root_admin"],
          badge: "Admin",
        },
      ],
    },
    {
      id: "security_admin",
      label: "Security Administration",
      items: [
        {
          title: "Security Settings",
          url: "/security-settings",
          icon: Shield,
          roles: ["admin", "root_admin"],
        },
        {
          title: "Security Monitoring",
          url: "/security-monitoring",
          icon: Shield,
          roles: ["root_admin"],
          badge: "Admin",
        },
        {
          title: "Rate Limiting",
          url: "/rate-limiting",
          icon: Settings,
          roles: ["root_admin"],
          badge: "Admin",
        },
      ],
    },
  ],
};
