-- Company tables a client_portal user can read in their contractor's company
-- beyond their own rows (US-394), as found by role_escalation.test.sql.
--
-- US-394 pinned 205 tables here: invite-client gives the client the
-- contractor's company_id, and each table had a policy admitting any member of
-- the company without looking at role. 20260924250000_client_portal_allowlist
-- closed all of them with AS RESTRICTIVE policies: a client_portal user reads
-- the portal's allowlisted tables only for projects they are enrolled on, and
-- nothing else. The probe enrols the client in nothing, so it reads nothing.
--
-- Empty now, and it may only stay empty. A new table that admits a client
-- fails role_escalation.test.sql; give it a client_portal_boundary policy
-- (see the header of 20260924250000) rather than listing it here.
--
-- Rows, if one is ever unavoidable, go in as:
--   INSERT INTO rls_test.client_visible_baseline (tbl) VALUES ('<table>');
