import React, { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { toast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';

interface WarrantyClaimFormProps {
  claim?: any;
  onClose: () => void;
  onSave: () => void;
}

interface Warranty {
  id: string;
  item_name: string;
  manufacturer: string;
  project?: { name: string };
}

export const WarrantyClaimForm: React.FC<WarrantyClaimFormProps> = ({ claim, onClose, onSave }) => {
  const { userProfile } = useAuth();
  const [loading, setLoading] = useState(false);
  const [warranties, setWarranties] = useState<Warranty[]>([]);

  const [formData, setFormData] = useState({
    warranty_id: claim?.warranty_id || '',
    issue_description: claim?.issue_description || '',
    issue_category: claim?.issue_category || 'defect',
    severity: claim?.severity || 'medium',
    claimant_name: claim?.claimant_name || '',
    claimant_contact: claim?.claimant_contact || '',
    claimant_email: claim?.claimant_email || '',
    claim_date: claim?.claim_date || new Date().toISOString().split('T')[0],
    status: claim?.status || 'submitted',
    resolution_type: claim?.resolution_type || '',
    resolution_details: claim?.resolution_details || '',
    resolution_cost: claim?.resolution_cost || 0,
    resolved_date: claim?.resolved_date || '',
    resolved_by: claim?.resolved_by || ''
  });

  useEffect(() => {
    loadWarranties();
  }, []);

  const loadWarranties = async () => {
    try {
      const { data, error } = await supabase
        .from('warranties')
        .select(`
          id,
          item_name,
          manufacturer,
          project:projects(name)
        `)
        .eq('company_id', userProfile?.company_id)
        .eq('status', 'active');

      if (error) throw error;
      setWarranties(data || []);
    } catch (error) {
      console.error('Error loading warranties:', error);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (claim) {
        // Update existing claim
        const updateData = {
          ...formData,
          created_by: userProfile?.id,
          resolution_cost: parseFloat(formData.resolution_cost.toString()) || 0
        };
        
        const { error } = await supabase
          .from('warranty_claims')
          .update(updateData)
          .eq('id', claim.id);

        if (error) throw error;

        toast({
          title: "Claim Updated",
          description: "The warranty claim has been updated successfully"
        });
      } else {
        // Create new claim - claim_number is auto-generated by database trigger
        const insertData = {
          warranty_id: formData.warranty_id,
          issue_description: formData.issue_description,
          issue_category: formData.issue_category,
          severity: formData.severity,
          claimant_name: formData.claimant_name,
          claimant_contact: formData.claimant_contact,
          claimant_email: formData.claimant_email,
          claim_date: formData.claim_date,
          status: formData.status,
          resolution_type: formData.resolution_type,
          resolution_details: formData.resolution_details,
          resolved_date: formData.resolved_date,
          resolved_by: formData.resolved_by,
          created_by: userProfile?.id,
          resolution_cost: parseFloat(formData.resolution_cost.toString()) || 0,
          claim_number: '' // Required by types but will be auto-generated
        };
        
        const { error } = await supabase
          .from('warranty_claims')
          .insert(insertData);

        if (error) throw error;

        toast({
          title: "Claim Filed",
          description: "The warranty claim has been filed successfully"
        });
      }

      onSave();
    } catch (error: any) {
      console.error('Error saving warranty claim:', error);
      toast({
        variant: "destructive",
        title: "Save Failed",
        description: error.message || "Failed to save warranty claim"
      });
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (field: string, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const issueCategories = [
    { value: 'defect', label: 'Manufacturing Defect' },
    { value: 'malfunction', label: 'Malfunction' },
    { value: 'premature_failure', label: 'Premature Failure' },
    { value: 'installation_error', label: 'Installation Error' },
    { value: 'other', label: 'Other' }
  ];

  const severityLevels = [
    { value: 'low', label: 'Low' },
    { value: 'medium', label: 'Medium' },
    { value: 'high', label: 'High' },
    { value: 'critical', label: 'Critical' }
  ];

  const statuses = [
    { value: 'submitted', label: 'Submitted' },
    { value: 'under_review', label: 'Under Review' },
    { value: 'approved', label: 'Approved' },
    { value: 'denied', label: 'Denied' },
    { value: 'in_progress', label: 'In Progress' },
    { value: 'resolved', label: 'Resolved' },
    { value: 'closed', label: 'Closed' }
  ];

  const resolutionTypes = [
    { value: 'repair', label: 'Repair' },
    { value: 'replace', label: 'Replace' },
    { value: 'refund', label: 'Refund' },
    { value: 'credit', label: 'Credit' },
    { value: 'no_action', label: 'No Action Required' }
  ];

  return (
    <Dialog open={true} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{claim ? 'Edit Warranty Claim' : 'File New Warranty Claim'}</DialogTitle>
          <DialogDescription>
            {claim ? 'Update warranty claim information' : 'File a new warranty claim'}
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="warranty_id">Warranty *</Label>
              <Select
                value={formData.warranty_id}
                onValueChange={(value) => handleInputChange('warranty_id', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select warranty" />
                </SelectTrigger>
                <SelectContent>
                  {warranties.map(warranty => (
                    <SelectItem key={warranty.id} value={warranty.id}>
                      {warranty.item_name} - {warranty.manufacturer}
                      {warranty.project?.name && ` (${warranty.project.name})`}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="claim_date">Claim Date *</Label>
              <Input
                id="claim_date"
                type="date"
                value={formData.claim_date}
                onChange={(e) => handleInputChange('claim_date', e.target.value)}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="issue_category">Issue Category *</Label>
              <Select
                value={formData.issue_category}
                onValueChange={(value) => handleInputChange('issue_category', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select issue category" />
                </SelectTrigger>
                <SelectContent>
                  {issueCategories.map(category => (
                    <SelectItem key={category.value} value={category.value}>
                      {category.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="severity">Severity *</Label>
              <Select
                value={formData.severity}
                onValueChange={(value) => handleInputChange('severity', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select severity" />
                </SelectTrigger>
                <SelectContent>
                  {severityLevels.map(level => (
                    <SelectItem key={level.value} value={level.value}>
                      {level.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="issue_description">Issue Description *</Label>
            <Textarea
              id="issue_description"
              value={formData.issue_description}
              onChange={(e) => handleInputChange('issue_description', e.target.value)}
              placeholder="Detailed description of the issue"
              rows={4}
              required
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label htmlFor="claimant_name">Claimant Name *</Label>
              <Input
                id="claimant_name"
                value={formData.claimant_name}
                onChange={(e) => handleInputChange('claimant_name', e.target.value)}
                placeholder="Person filing the claim"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="claimant_contact">Claimant Phone</Label>
              <Input
                id="claimant_contact"
                value={formData.claimant_contact}
                onChange={(e) => handleInputChange('claimant_contact', e.target.value)}
                placeholder="Phone number"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="claimant_email">Claimant Email</Label>
              <Input
                id="claimant_email"
                type="email"
                value={formData.claimant_email}
                onChange={(e) => handleInputChange('claimant_email', e.target.value)}
                placeholder="Email address"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="status">Status</Label>
              <Select
                value={formData.status}
                onValueChange={(value) => handleInputChange('status', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  {statuses.map(status => (
                    <SelectItem key={status.value} value={status.value}>
                      {status.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="resolution_type">Resolution Type</Label>
              <Select
                value={formData.resolution_type}
                onValueChange={(value) => handleInputChange('resolution_type', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select resolution type" />
                </SelectTrigger>
                <SelectContent>
                  {resolutionTypes.map(type => (
                    <SelectItem key={type.value} value={type.value}>
                      {type.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="resolution_details">Resolution Details</Label>
            <Textarea
              id="resolution_details"
              value={formData.resolution_details}
              onChange={(e) => handleInputChange('resolution_details', e.target.value)}
              placeholder="Details about the resolution"
              rows={3}
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label htmlFor="resolution_cost">Resolution Cost</Label>
              <Input
                id="resolution_cost"
                type="number"
                step="0.01"
                min="0"
                value={formData.resolution_cost}
                onChange={(e) => handleInputChange('resolution_cost', e.target.value)}
                placeholder="0.00"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="resolved_date">Resolved Date</Label>
              <Input
                id="resolved_date"
                type="date"
                value={formData.resolved_date}
                onChange={(e) => handleInputChange('resolved_date', e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="resolved_by">Resolved By</Label>
              <Input
                id="resolved_by"
                value={formData.resolved_by}
                onChange={(e) => handleInputChange('resolved_by', e.target.value)}
                placeholder="Person who resolved the issue"
              />
            </div>
          </div>

          <div className="flex justify-end space-x-2">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={loading}>
              {loading ? 'Saving...' : claim ? 'Update Claim' : 'File Claim'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};