import React from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Form } from '@/components/ui/form';
import { InputFormField, SelectFormField, TextareaFormField } from '@/components/forms/FormFields';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  buildWarrantyClaimInsert,
  buildWarrantyClaimUpdate,
  warrantyClaimFormDefaults,
  warrantyClaimFormSchema,
  type WarrantyClaimFormValues,
} from '@/lib/validations/warranty';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { toast } from '@/hooks/use-toast';
import { useSaveCompanyRecord, useActiveWarranties } from '@/hooks/useRecordForms';

interface WarrantyClaimFormProps {
  claim?: any;
  onClose: () => void;
  onSave: () => void;
}


export const WarrantyClaimForm: React.FC<WarrantyClaimFormProps> = ({ claim, onClose, onSave }) => {
  const { userProfile } = useAuth();

  const form = useForm<WarrantyClaimFormValues>({
    resolver: zodResolver(warrantyClaimFormSchema),
    defaultValues: warrantyClaimFormDefaults(claim),
  });

  const save = useSaveCompanyRecord('warranty_claims');
  const warrantiesQuery = useActiveWarranties();
  const warranties = warrantiesQuery.data ?? [];

  const handleSubmit = async (values: WarrantyClaimFormValues) => {
    try {
      if (claim) {
        // Update existing claim
        const updateData = buildWarrantyClaimUpdate(values, userProfile);
        
        await save.mutateAsync({ id: claim.id, row: updateData });

        toast({
          title: "Claim Updated",
          description: "The warranty claim has been updated successfully"
        });
      } else {
        // Create new claim - claim_number is auto-generated by database trigger
        const insertData = buildWarrantyClaimInsert(values, userProfile);
        
        await save.mutateAsync({ row: insertData });

        toast({
          title: "Claim Filed",
          description: "The warranty claim has been filed successfully"
        });
      }

      onSave();
    } catch (error: any) {
      console.error('Error saving warranty claim:', error);
      toast({
        variant: "destructive",
        title: "Save Failed",
        description: error.message || "Failed to save warranty claim"
      });
    }
  };

  const issueCategories = [
    { value: 'defect', label: 'Manufacturing Defect' },
    { value: 'malfunction', label: 'Malfunction' },
    { value: 'premature_failure', label: 'Premature Failure' },
    { value: 'installation_error', label: 'Installation Error' },
    { value: 'other', label: 'Other' }
  ];

  const severityLevels = [
    { value: 'low', label: 'Low' },
    { value: 'medium', label: 'Medium' },
    { value: 'high', label: 'High' },
    { value: 'critical', label: 'Critical' }
  ];

  const statuses = [
    { value: 'submitted', label: 'Submitted' },
    { value: 'under_review', label: 'Under Review' },
    { value: 'approved', label: 'Approved' },
    { value: 'denied', label: 'Denied' },
    { value: 'in_progress', label: 'In Progress' },
    { value: 'resolved', label: 'Resolved' },
    { value: 'closed', label: 'Closed' }
  ];

  const resolutionTypes = [
    { value: 'repair', label: 'Repair' },
    { value: 'replace', label: 'Replace' },
    { value: 'refund', label: 'Refund' },
    { value: 'credit', label: 'Credit' },
    { value: 'no_action', label: 'No Action Required' }
  ];

  return (
    <Dialog open={true} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{claim ? 'Edit Warranty Claim' : 'File New Warranty Claim'}</DialogTitle>
          <DialogDescription>
            {claim ? 'Update warranty claim information' : 'File a new warranty claim'}
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
        <form onSubmit={form.handleSubmit(handleSubmit)} noValidate className="space-y-6" aria-label="Warranty claim form">
          {(warrantiesQuery.error) && (
            <p role="alert" className="text-sm text-destructive">
              Warranties could not be loaded: {(warrantiesQuery.error)?.message}
            </p>
          )}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <SelectFormField
              control={form.control}
              name="warranty_id"
              label="Warranty *"
              placeholder="Select warranty"
              options={warranties.map((w) => ({
                value: w.id,
                label: (
                  <>
                    {w.item_name} - {w.manufacturer}
                    {w.project?.name && ` (${w.project.name})`}
                  </>
                ),
              }))}
            />
            <InputFormField control={form.control} name="claim_date" label="Claim Date *" type="date" aria-required="true" />
            <SelectFormField control={form.control} name="issue_category" label="Issue Category *" placeholder="Select issue category" options={issueCategories} />
            <SelectFormField control={form.control} name="severity" label="Severity *" placeholder="Select severity" options={severityLevels} />
          </div>

          <TextareaFormField control={form.control} name="issue_description" label="Issue Description *" placeholder="Detailed description of the issue" rows={4} />

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <InputFormField control={form.control} name="claimant_name" label="Claimant Name *" placeholder="Person filing the claim" aria-required="true" />
            <InputFormField control={form.control} name="claimant_contact" label="Claimant Phone" placeholder="Phone number" />
            <InputFormField control={form.control} name="claimant_email" label="Claimant Email" type="email" placeholder="Email address" />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <SelectFormField control={form.control} name="status" label="Status" placeholder="Select status" options={statuses} />
            <SelectFormField control={form.control} name="resolution_type" label="Resolution Type" placeholder="Select resolution type" options={resolutionTypes} />
          </div>

          <TextareaFormField control={form.control} name="resolution_details" label="Resolution Details" placeholder="Details about the resolution" rows={3} />

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <InputFormField control={form.control} name="resolution_cost" label="Resolution Cost" type="number" step="0.01" min="0" placeholder="0.00" />
            <InputFormField control={form.control} name="resolved_date" label="Resolved Date" type="date" />
            <InputFormField control={form.control} name="resolved_by" label="Resolved By" placeholder="Person who resolved the issue" />
          </div>

          <div className="flex justify-end space-x-2">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={save.isPending}>
              {save.isPending ? 'Saving...' : claim ? 'Update Claim' : 'File Claim'}
            </Button>
          </div>
        </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};