import React from 'react';
import { Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

/**
 * Marks content that a model produced or materially shaped.
 *
 * The AI Disclosure (src/pages/legal/AIDisclosure.tsx) commits to labelling
 * AI-assisted output in the product. Before this existed the labelling was
 * ad-hoc prose on a handful of surfaces and absent elsewhere, so the
 * commitment was broader than the behaviour. This is the one component that
 * commitment points at.
 *
 * Accessibility: the meaning is carried by the text, not by the icon or the
 * colour, so it survives a screen reader and a monochrome display. The icon is
 * decorative and hidden from assistive tech.
 */
export interface AIGeneratedBadgeProps {
  /** Override the label where a more precise word fits, e.g. "AI estimate". */
  label?: string;
  /** Longer explanation surfaced as the accessible title. */
  title?: string;
  className?: string;
  variant?: React.ComponentProps<typeof Badge>['variant'];
}

export const AIGeneratedBadge: React.FC<AIGeneratedBadgeProps> = ({
  label = 'Generated by AI',
  title = 'This content was generated or materially assisted by AI. Review it before relying on it.',
  className,
  variant = 'secondary',
}) => (
  <Badge
    variant={variant}
    title={title}
    className={cn('gap-1 font-normal', className)}
  >
    <Sparkles className="h-3 w-3" aria-hidden="true" />
    {label}
  </Badge>
);

export default AIGeneratedBadge;
